### ISSUE TITLE
how to complete list of chat with getdialogs???

### ISSUE THREAD

**Issue by Ansel1234S** [Starli0n/TLArchiver#1]
how to complete list of chat with getdialogs???
i use get dialog Method . My Telegram Account Has More Than 350 Groups,I want to get All Chats,But That's Method Can Not Give All Chat, sometimes Get 120 Chats, Sometimes 125 Chats, No more than 350 Chats, Please Example Method For Resolve My Problem. Thank you

**Comment by Starli0n** [comment]
For getting the list of dialogs linked to your contact list, use `GetContactsAsync()` from the TLSharp lib.
You have an example in my code[`GetContacts()`](https://github.com/Starli0n/TLArchiver/blob/master/TLArchiver/Core/TLAArchiver.cs#L112)
This method returns a `TLUser`.

For getting the list of groups or channels, use `GetUserDialogsAsync()` from the TLSharp lib.
You have an example in my code [`GetUserDialogs()`](https://github.com/Starli0n/TLArchiver/blob/master/TLArchiver/Core/TLAArchiver.cs#L133)

As you can see, this method could return four type of dialogs:
`TLChat`, `TLChannel`, `TLChatForbidden` or `TLChannelForbidden`.

From what I understood `TL~Forbidden` stands for `closed`.

**Comment by Ansel1234S** [comment]
i want get all groups,My Telegram Account Has More Than 350 Groups
Please help

**Comment by Starli0n** [comment]
My app `TLArchiver` should do the job.

Otherwise develop your own using `GetUserDialogsAsync()` from the TLSharp lib.
